### ISSUE TITLE
Option to ignore certain files?

### ISSUE THREAD

**Issue by joereynolds** [mhinz/vim-randomtag#3]
It'd be good if we could tell it to not open certain files. For example, I work only with terminal vim and do not care about `gui.txt` or a few other folders

**Comment by mhinz** [comment]
Actually I'd like to avoid adding options for this rather simple plugin. :-)

But if you're not opposed to some VimL in your vimrc, you could redefine the `:Random` command like this:

```vim
autocmd VimEnter * command! -nargs=0 -bang -bar Random call s:randomtag(<bang>0)

function! s:randomtag(bang) abort
  let blacklist = ['gui', 'opt', 'eval']

  while 1
    execute 'help' randomtag#tag(a:bang)
    let helpfile = expand('%:t')
    if len(filter(copy(blacklist), 'helpfile =~ v:val'))
      continue
    endif
    break
  endwhile
endfunction
```

So, if you land in either `gui.txt`, `options.txt`, or `eval.txt`, it will simply jump to the next random tag.

**Comment by joereynolds** [comment]
That's great, thanks!
